name: Bug Report
description: File a bug report to help us improve HaemoLogix
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what went wrong
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here

  - type: dropdown
    id: user-role
    attributes:
      label: User Role
      description: Which role were you using when you encountered this bug?
      options:
        - Donor
        - Hospital
        - Admin
        - Guest/Public
        - Other
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      placeholder: e.g., Chrome 120, Firefox 121, Safari 17
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which OS are you using?
      placeholder: e.g., Windows 11, macOS 14, Ubuntu 22.04, iOS 17, Android 14
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Device Type
      description: What type of device are you using?
      options:
        - Desktop
        - Mobile
        - Tablet
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Console Errors/Logs
      description: If applicable, paste any console errors or logs
      render: shell
      placeholder: Paste console errors here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Before submitting, please confirm
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am using the latest version of HaemoLogix
          required: true
        - label: This issue is reproducible
          required: false

